# Generated by Django 4.2.7 on 2025-04-19 13:37

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('flag_image', models.ImageField(upload_to='offices/flags/')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', django_bleach.models.BleachField(verbose_name='Description')),
                ('fresh_image', models.ImageField(blank=True, null=True, upload_to='products/fresh/')),
                ('iqf_image', models.ImageField(blank=True, null=True, upload_to='products/iqf/')),
                ('product_type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF'), ('both', 'Both Fresh & IQF')], default='both', max_length=10)),
                ('has_varieties', models.BooleanField(default=False)),
                ('has_counts', models.BooleanField(default=False)),
                ('has_size', models.BooleanField(default=False)),
                ('has_packaging', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_in_slider', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', django_bleach.models.BleachField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/varieties/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variety',
                'verbose_name_plural': 'Product Varieties',
            },
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('jan', models.BooleanField(default=False, verbose_name='January')),
                ('feb', models.BooleanField(default=False, verbose_name='February')),
                ('mar', models.BooleanField(default=False, verbose_name='March')),
                ('apr', models.BooleanField(default=False, verbose_name='April')),
                ('may', models.BooleanField(default=False, verbose_name='May')),
                ('jun', models.BooleanField(default=False, verbose_name='June')),
                ('jul', models.BooleanField(default=False, verbose_name='July')),
                ('aug', models.BooleanField(default=False, verbose_name='August')),
                ('sep', models.BooleanField(default=False, verbose_name='September')),
                ('oct', models.BooleanField(default=False, verbose_name='October')),
                ('nov', models.BooleanField(default=False, verbose_name='November')),
                ('dec', models.BooleanField(default=False, verbose_name='December')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonality', to='products.product')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonality', to='products.productvariety')),
            ],
            options={
                'verbose_name': 'Seasonality',
                'verbose_name_plural': 'Seasonalities',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('cartons_per_pallet', models.PositiveIntegerField(default=0)),
                ('pallets_per_container', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Packaging',
                'verbose_name_plural': 'Product Packaging',
            },
        ),
        migrations.CreateModel(
            name='ProductCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Count',
                'verbose_name_plural': 'Product Counts',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('contact', 'Contact Message'), ('quote', 'Quote Request')], default='contact', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='seasonality',
            constraint=models.CheckConstraint(check=models.Q(('product__isnull', False), ('variety__isnull', False), _connector='OR'), name='seasonality_product_or_variety'),
        ),
    ]
