# Generated by Django 4.2.7 on 2025-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_left',
            field=models.ImageField(blank=True, null=True, upload_to='products/backgrounds/'),
        ),
        migrations.AddField(
            model_name='product',
            name='background_right',
            field=models.ImageField(blank=True, null=True, upload_to='products/backgrounds/'),
        ),
        migrations.AddField(
            model_name='product',
            name='fresh_packaging_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/packaging/'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='iqf_packaging_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/packaging/'),
        ),
    ]
