# Generated by Django 4.2.7 on 2025-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_background_left_product_background_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fresh_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iqf_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
