# Generated by Django 4.2.7 on 2025-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_fresh_image_alter_product_iqf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iqf_icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/list/'),
        ),
    ]
