# Generated by Django 4.2.7 on 2025-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=models.CharField(blank=True, help_text='HEX color code for product button (e.g. #5cbcaa)', max_length=20, verbose_name='Button Color'),
        ),
    ]
