# Generated by Django 4.2.7 on 2025-04-19 17:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='HEX color code for product button (e.g. #5cbcaa)', image_field=None, max_length=25, samples=None, verbose_name='Button Color'),
        ),
    ]
