# Generated by Django 4.2.7 on 2025-04-19 17:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#5cbcaa', help_text='Choose a color for the product button', image_field=None, max_length=18, samples=None, verbose_name='Button Color'),
        ),
    ]
