# Generated by Django 4.2.7 on 2025-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=models.CharField(blank=True, help_text='Choose a color for the product button', max_length=7, verbose_name='Button Color'),
        ),
    ]
