# Generated by Django 4.2.7 on 2025-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_button_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_quantity', models.CharField(max_length=50)),
                ('requested_specifications', models.TextField(blank=True)),
                ('target_price_range', models.CharField(blank=True, max_length=100)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='product_requests/attachments/')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Request',
                'verbose_name_plural': 'Product Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to='products/season_icons/')),
                ('color_code', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Season Icon',
                'verbose_name_plural': 'Season Icons',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
