# Generated by Django 4.2.7 on 2025-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productrequest_seasonicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/sizes/')),
            ],
            options={
                'verbose_name': 'Size Option',
                'verbose_name_plural': 'Size Options',
                'ordering': ['name'],
                'unique_together': {('value', 'unit', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PackagingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('cartons_per_pallet', models.PositiveIntegerField(default=0)),
                ('pallets_per_container', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/packaging_options/')),
            ],
            options={
                'verbose_name': 'Packaging Option',
                'verbose_name_plural': 'Packaging Options',
                'ordering': ['name'],
                'unique_together': {('name', 'type', 'net_weight', 'weight_unit')},
            },
        ),
        migrations.CreateModel(
            name='CountOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/counts/')),
            ],
            options={
                'verbose_name': 'Count Option',
                'verbose_name_plural': 'Count Options',
                'ordering': ['name'],
                'unique_together': {('value', 'unit', 'type')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_counts',
            field=models.ManyToManyField(blank=True, related_name='products_with_count', to='products.countoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_packaging',
            field=models.ManyToManyField(blank=True, related_name='products_with_packaging', to='products.packagingoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products_with_size', to='products.sizeoption'),
        ),
    ]
