# Generated by Django 4.2.7 on 2025-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sizeoption_packagingoption_countoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countoption',
            options={'ordering': ['value'], 'verbose_name': 'Count Option', 'verbose_name_plural': 'Count Options'},
        ),
        migrations.AlterUniqueTogether(
            name='countoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='countoption',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductCount',
        ),
        migrations.RemoveField(
            model_name='countoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='countoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='countoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='countoption',
            name='type',
        ),
        migrations.RemoveField(
            model_name='countoption',
            name='unit',
        ),
    ]
