# Generated by Django 4.2.7 on 2025-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_countoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeoption',
            options={'ordering': ['value'], 'verbose_name': 'Size Option', 'verbose_name_plural': 'Size Options'},
        ),
        migrations.AlterUniqueTogether(
            name='sizeoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='unit',
        ),
    ]
