# Generated by Django 4.2.7 on 2025-04-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_sizeoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Packaging Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/packaging_types/', verbose_name='Packaging Image')),
                ('key_word', models.CharField(help_text="المصطلح المميز مثل 'boxes', 'cartons' إلخ", max_length=50, verbose_name='Key Word')),
                ('is_fresh', models.BooleanField(default=True, verbose_name='For Fresh Products')),
                ('is_iqf', models.BooleanField(default=True, verbose_name='For IQF Products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF')], default='fresh', max_length=10, verbose_name='Product Type')),
                ('pallets_per_container', models.PositiveIntegerField(default=0, verbose_name='Pallets per Container')),
                ('items_per_pallet', models.PositiveIntegerField(default=0, verbose_name='Items per Pallet')),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Weight')),
                ('weight_unit', models.CharField(default='kg', max_length=10, verbose_name='Weight Unit')),
                ('show_fresh_label', models.BooleanField(default=True, help_text='عرض عنوان Fresh فوق مربع التغليف (فقط للمنتجات الطازجة)', verbose_name='Show Fresh Label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packaging_types', to='products.packagingtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packaging_types', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Packaging Type',
                'verbose_name_plural': 'Product Packaging Types',
                'ordering': ['product', 'packaging_type'],
                'unique_together': {('product', 'packaging_type', 'type')},
            },
        ),
    ]
