# Generated by Django 4.2.7 on 2025-04-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_packagingtype_productpackagingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countoption',
            name='value',
            field=models.FloatField(unique=True),
        ),
    ]
