# Generated by Django 4.2.7 on 2025-04-21 13:50

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_countoption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fresh_description',
            field=django_bleach.models.BleachField(blank=True, help_text='وصف خاص بالمنتج الطازج فقط', null=True, verbose_name='Fresh Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='iqf_description',
            field=django_bleach.models.BleachField(blank=True, help_text='وصف خاص بالمنتج المجمد فقط', null=True, verbose_name='IQF Description'),
        ),
        migrations.AlterField(
            model_name='countoption',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
