# Generated by Django 4.2.7 on 2025-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('iqf', 'IQF'), ('both', 'Both Fresh & IQF'), ('general', 'General')], default='both', max_length=10),
        ),
    ]
