# Generated by Django 4.2.7 on 2025-04-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonality',
            name='season_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonalities', to='products.seasonicon', verbose_name='Seasonality Icon'),
        ),
    ]
