# Generated by Django 4.2.7 on 2025-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_seasonality_season_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonality',
            name='season_icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/seasonality_icons/', verbose_name='Seasonality Icon'),
        ),
    ]
