# Generated by Django 4.2.7 on 2025-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_seasonality_season_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seasonality_icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/seasonality_icons/', verbose_name='Seasonality Icon'),
        ),
    ]
