# Generated by Django 4.2.7 on 2025-04-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_seasonality_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countoption',
            options={'ordering': ['numeric_sort', 'value'], 'verbose_name': 'Count Option', 'verbose_name_plural': 'Count Options'},
        ),
        migrations.AddField(
            model_name='countoption',
            name='numeric_sort',
            field=models.IntegerField(blank=True, help_text='قيمة رقمية للترتيب', null=True),
        ),
        migrations.AlterField(
            model_name='productpackagingtype',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Weight'),
        ),
    ]
