# Generated by Django 4.2.7 on 2025-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_countoption_options_countoption_numeric_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the product on the product page (lower numbers appear first)'),
        ),
    ]
