# Generated by Django 4.2.7 on 2025-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='صورة خلفية كاملة للمنتج المخصوص', null=True, upload_to='products/backgrounds/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار إذا كان المنتج مخصوصًا بتصميم مختلف', verbose_name='Special Product'),
        ),
    ]
