# Generated by Django 4.2.7 on 2025-04-24 07:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_bg_image_product_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#5cbcaa', help_text='Choose a color for the product button', image_field=None, max_length=18, samples=None, verbose_name='Button Color'),
        ),
    ]
