# Generated by Django 4.2.7 on 2025-04-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_update_empty_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackagingtype',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='productpackagingtype',
            name='weight_unit',
        ),
    ]
