# Generated by Django 4.2.7 on 2025-04-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_productpackagingtype_net_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackagingtype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب ظهور البوكس (الأرقام الأصغر تظهر أولاً)', verbose_name='Display Order'),
        ),
    ]
