# Generated by Django 4.2.7 on 2025-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_add_display_order_to_productpackagingtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackagingtype',
            options={'ordering': ['type', 'order', 'product', 'packaging_type'], 'verbose_name': 'Product Packaging Type', 'verbose_name_plural': 'Product Packaging Types'},
        ),
        migrations.RemoveField(
            model_name='productpackagingtype',
            name='display_order',
        ),
        migrations.AddField(
            model_name='productpackagingtype',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب ظهور نوع التغليف في الصفحة (الأرقام الأصغر تظهر أولاً)', verbose_name='Display Order'),
        ),
    ]
