# Generated by Django 4.2.7 on 2025-04-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_productpackagingtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_inquiries', to='products.product'),
        ),
    ]
