# Generated by Django 4.2.20 on 2025-04-26 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_notes', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry Note',
                'verbose_name_plural': 'Inquiry Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
