# Generated by Django 4.2.7 on 2025-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='اسم الدولة')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='علم الدولة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['display_order', 'country_name'],
            },
        ),
    ]
