# Generated by Django 4.2.7 on 2025-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['display_order'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='flag',
        ),
        migrations.AddField(
            model_name='branch',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Country Flag'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country_name',
            field=models.CharField(max_length=100, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
    ]
