# Generated by Django 4.2.7 on 2025-04-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_remove_branch_flag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
