"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# إعداد environ
env = environ.Env(
    # القيمة الافتراضية للـ DEBUG هي False إذا لم يتم تحديدها في ملف .env
    DEBUG=(bool, False),
    SECRET_KEY=(str, 'default-insecure-key-change-in-production'),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    # إعدادات البريد الإلكتروني
    EMAIL_BACKEND=(str, 'django.core.mail.backends.smtp.EmailBackend'),
    EMAIL_HOST=(str, 'localhost'),
    EMAIL_PORT=(int, 25),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_USE_TLS=(bool, False),
    CONTACT_EMAIL=(str, 'info@egyland.com'),
    # إعداد وضع البناء
    UNDER_CONSTRUCTION=(bool, True),
)

# نحاول قراءة ملف .env إذا كان موجودًا
environ.Env.read_env(os.path.join(os.path.dirname(__file__), '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    # تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # تطبيقات خارجية
    'crispy_forms',
    'crispy_tailwind',
    'debug_toolbar',
    'compressor',
    'colorfield',
    
    # تطبيقات المشروع
    'apps.accounts',
    'apps.core',
    'apps.products',
    'apps.dashboard.apps.DashboardConfig',
    'apps.branches.apps.BranchesConfig',
    'apps.inquiries.apps.InquiriesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # للملفات الثابتة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # شريط التصحيح
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # إضافة سياق مخصص للشركة
                'apps.core.context_processors.company_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Uncomment this to use PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('DB_NAME', default='egyland'),
#         'USER': env('DB_USER', default='postgres'),
#         'PASSWORD': env('DB_PASSWORD', default='postgres'),
#         'HOST': env('DB_HOST', default='localhost'),
#         'PORT': env('DB_PORT', default='5432'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# إعدادات Whitenoise لخدمة الملفات الثابتة
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# إعدادات وسائط المستخدم
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# إعداد Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'tailwind'
CRISPY_TEMPLATE_PACK = 'tailwind'

# إعدادات Django Debug Toolbar
INTERNAL_IPS = ['127.0.0.1']
# تعطيل Debug Toolbar مؤقتًا
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: False,
}

# إعدادات Django Compressor
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# ملفات مستثناة من الضغط - تحديد نمط أكثر دقة
COMPRESS_EXCLUDE_FILES = [
    'product_detail.html',   # استثناء بالاسم المحدد
    'products/product_detail.html',  # المسار النسبي
    'templates/products/product_detail.html',  # المسار الكامل
]

# تعطيل الضغط التلقائي للملفات بالكامل في وضع التطوير
if DEBUG:
    COMPRESS_ENABLED = False
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ('png', 'jpg', 'jpeg', 'gif', 'svg', 'woff', 'woff2', 'ttf', 'eot', 'pdf', 'html')

# إعدادات تنظيف HTML والحفاظ على التعليقات
KEEP_COMMENTS_ON_MINIFYING = True
HTML_MINIFY = False  # تعطيل ضغط HTML تماماً
EXCLUDE_FROM_MINIFYING = ('products/product_detail.html',)
HTML_MINIFY_EXEMPT = ['/products/*']  # استثناء كل صفحات المنتجات

# إعدادات Bleach لتنظيف المحتوى
BLEACH_ALLOWED_TAGS = ['p', 'b', 'i', 'u', 'em', 'strong', 'a', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
                      'ul', 'ol', 'li', 'span', 'div', 'br', 'hr', 'table', 'tbody', 'thead', 'tr', 'td', 'th',
                      'img', 'blockquote', 'pre', 'code', 'figure', 'figcaption']
                      
BLEACH_ALLOWED_ATTRIBUTES = {
    'a': ['href', 'title', 'target', 'rel'],
    'img': ['src', 'alt', 'width', 'height', 'style'],
    'span': ['style', 'class'],
    'div': ['style', 'class'],
    'p': ['style', 'class'],
    'table': ['border', 'cellpadding', 'cellspacing', 'width', 'style', 'class'],
    'th': ['scope', 'colspan', 'rowspan', 'style', 'class'],
    'td': ['colspan', 'rowspan', 'style', 'class'],
}

BLEACH_ALLOWED_STYLES = [
    'font-family', 'font-size', 'font-weight', 'text-decoration', 'text-align',
    'color', 'background-color', 'margin', 'padding', 'border', 'width', 'height',
    'margin-left', 'margin-right', 'margin-top', 'margin-bottom', 'float',
    'display', 'position', 'top', 'left', 'right', 'bottom', 'vertical-align',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات التسجيل Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/egyland.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# إعدادات البريد الإلكتروني
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = 'Egyland <noreply@egyland.com>'

# عنوان البريد الإلكتروني للاتصال والاستفسارات
CONTACT_EMAIL = env('CONTACT_EMAIL', default='info@egyland.com')

# إعدادات المصادقة
LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'

# إعدادات تنظيف HTML والحفاظ على التعليقات
KEEP_COMMENTS_ON_MINIFYING = True
HTML_MINIFY = False  # تعطيل ضغط HTML تماماً
EXCLUDE_FROM_MINIFYING = ('products/product_detail.html',)
HTML_MINIFY_EXEMPT = ['/products/*']  # استثناء كل صفحات المنتجات 