# Generated by Django 4.2.20 on 2025-04-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
