# Generated by Django 4.2.7 on 2025-05-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_role_can_manage_roles_role_can_manage_users'),
    ]
    
    operations = [
        # محاولة إضافة assigned_at إذا لم يكن موجوداً
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    SELECT CASE 
                        WHEN NOT EXISTS(SELECT 1 FROM pragma_table_info('user_management_userrole') WHERE name='assigned_at') 
                        THEN 'ALTER TABLE user_management_userrole ADD COLUMN assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL'
                    END;
                    """,
                    reverse_sql=""
                ),
            ],
            state_operations=[
                # لا نحتاج إلى تغيير state لأن الموديل أصلاً يحتوي على assigned_at
            ]
        ),
    ] 