# Generated by Django 4.2.7 on 2025-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Company Logo')),
                ('address', models.TextField(verbose_name='Headquarters Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Number')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Commercial Registration Number')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Main Branch',
                'verbose_name_plural': 'Main Branch',
            },
        ),
    ]
